backend:
  name: git-gateway
  repo: "Nairb68/obr-blog"  # Remplacez par votre nom d'utilisateur et le nom de votre dépôt
  branch: main             # Utilisez "main" ou "master" selon votre branche principale
media_folder: "images/uploads"          # Dossier pour stocker vos images
public_folder: "/images/uploads"
collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
