backend:
  name: github
  repo: "votre-utilisateur/votre-repo"  # Remplacez par votre nom d'utilisateur et le nom de votre dépôt
  branch: main                          # Ou "master" si c'est le nom de votre branche principale
media_folder: "images/uploads"          # Dossier pour stocker vos images
public_folder: "/images/uploads"
collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"             # Dossier où seront stockés vos articles
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Contenu", name: "body", widget: "markdown" }
